# To train the Object detection Model:

In [1]:
from ultralytics import YOLO

# # Load a model
model = YOLO('yolov8x.pt')  # load a pretrained model (recommended for training)

# # Train the model with 2 GPUs
results = model.train(data='data.yaml', epochs=200, imgsz=640) 


# Test Object Detection Model:

In [2]:
from ultralytics import YOLO

# Load a pretrained YOLOv8n model
model = YOLO('best.pt')

# Run inference on 'bus.jpg' with arguments
model.predict('App Test Data/ANPR VIdeo.mp4', save=True, imgsz=320, conf=0.2)


c:\Users\Nawaz\Downloads\ANPR-App\ultralytics\nn\tasks.py:341: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(attempt_download(weight), map_location='cpu') 

[tensor([[1.06000e+03, 6.74000e+02, 1.57100e+03, 8.24000e+02, 8.44395e-01, 0.00000e+00]]),
 tensor([[1.06000e+03, 6.74000e+02, 1.57100e+03, 8.24000e+02, 8.44390e-01, 0.00000e+00]]),
 tensor([[1.06000e+03, 6.74000e+02, 1.57100e+03, 8.24000e+02, 8.44359e-01, 0.00000e+00]]),
 tensor([[1.06000e+03, 6.74000e+02, 1.57100e+03, 8.24000e+02, 8.44395e-01, 0.00000e+00]]),
 tensor([[1.06000e+03, 6.74000e+02, 1.57100e+03, 8.24000e+02, 8.44431e-01, 0.00000e+00]]),
 tensor([[1.06000e+03, 6.74000e+02, 1.57100e+03, 8.24000e+02, 8.44329e-01, 0.00000e+00]]),
 tensor([[1.06000e+03, 6.74000e+02, 1.57100e+03, 8.24000e+02, 8.44320e-01, 0.00000e+00]]),
 tensor([[1.06000e+03, 6.74000e+02, 1.57100e+03, 8.24000e+02, 8.44327e-01, 0.00000e+00]]),
 tensor([[1.06000e+03, 6.74000e+02, 1.57100e+03, 8.24000e+02, 8.44365e-01, 0.00000e+00]]),
 tensor([[1.06000e+03, 6.74000e+02, 1.57100e+03, 8.24000e+02, 8.44364e-01, 0.00000e+00]]),
 tensor([[1.06000e+03, 6.74000e+02, 1.57100e+03, 8.24000e+02, 8.44368e-01, 0.00000e+00]]),

# Recognize License plate after Detecting  using easy-ocr

In [1]:
#!pip install easyocr

In [2]:
!python predict_modified.py model='best.pt' source='ANPR Video.mp4' 

Ultralytics YOLOv8.0.3  Python-3.9.10 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24576MiB)
Fusing layers... 
Model summary: 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs
video 1/1 (1/672) D:\yolov8_license_plate_recog\License_plate_recognition\test_vid.mp4: 384x640 1 licence, 47.0ms
video 1/1 (2/672) D:\yolov8_license_plate_recog\License_plate_recognition\test_vid.mp4: 384x640 1 licence, 13.0ms
video 1/1 (3/672) D:\yolov8_license_plate_recog\License_plate_recognition\test_vid.mp4: 384x640 1 licence, 13.0ms
video 1/1 (4/672) D:\yolov8_license_plate_recog\License_plate_recognition\test_vid.mp4: 384x640 1 licence, 13.0ms
video 1/1 (5/672) D:\yolov8_license_plate_recog\License_plate_recognition\test_vid.mp4: 384x640 1 licence, 13.0ms
video 1/1 (6/672) D:\yolov8_license_plate_recog\License_plate_recognition\test_vid.mp4: 384x640 1 licence, 9.0ms
video 1/1 (7/672) D:\yolov8_license_plate_recog\License_plate_recognition\test_vid.mp4: 384x640 1 licence, 10.0ms
video 1/1 (8/67